services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - uploads:/mnt/uploads
      - ./app:/app/app  # For development - remove in production
    depends_on:
      - mongo
      - valkey
      - qdrant
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 1.1.1.1

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped


  valkey:
    image: valkey/valkey:latest
    ports:
      - "6379:6379"
    volumes:
      - valkey_data:/usr/local/etc/valkey
    restart: unless-stopped
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  mongodb_data:
  valkey_data:
  uploads:
  qdrant_data:

